// AUTO-GENERATED by scripts/extract-spec-notes.ts — do not edit by hand.
// Re-run: bun scripts/extract-spec-notes.ts
// Hand-written entries in `notes.ts` always win over these.

export const GENERATED_NOTES: Record<string, string> = {
  "ch1-01": `This overview explicitly addresses each of the 6 AI-readiness audit dimensions; every claim is load-bearing for the next audit run.

-- Frontend: src/components/<feature>/*.tsx, src/state/<feature>Store.ts, src/api/<feature>.ts (typed Axios calls from spec/32-ui-design/skeletons/ts/api-client.generated.ts).
-- Backend: wp-plugin/src/Rest/<Feature>Controller.php (signatures from spec/15-wp-plugin-how-to/skeletons/php/RestRoutes.generated.php), wp-plugin/src/Domain/<Feature>/*, wp-plugin/migrations/NNN-<feature>.sql.
-- Tests: one Vitest + one PHPUnit test per AT-* row in 97-acceptance-criteria.md and per-feature 97-acceptance-criteria.md files; test names MUST start with the AT id.
-- Fixtures: one JSON envelope per endpoint listed in 06-endpoints/ under 04a-fixtures/.
-- Visual styling tokens → 07-design-system/ and 32-ui-design/03-design-system/.

-- Source: spec/31-app/00-overview.md`,
  "ch1-02": `ItemType is a closed enum of exactly 12 values. No 13th value may be added without a superseding ADR.

-- mirror — Mirrors are rows in the Mirrors table referencing a source Items row. Mirror is a peer-group relation, not a turn-into target. Forbidden as an ItemType literal anywhere in spec/31-app/.
-- Root, root, page, document, note, task, project, embed, image, file, link, heading, template — none of these are members of ItemType. If any such literal appears in App-folder spec text, it is a bug (see §3).

-- Source: spec/31-app/00-itemtype-canonical.md`,
  "ch16-01-concurrency-ui": `This file is the single source of truth for how concurrent edits resolve across tabs, devices, and collaborators. Every other feature (mirrors, sharing, multi-select, today, board) defers to the rules here.

-- ❌ Mutating BrokenAt without also writing BrokenAtUpdatedAt = serverNow and BrokenAtUpdatedBy.
-- ❌ Resolving "broken vs healthy" with MAX(BrokenAt) — the comparison is on BrokenAtUpdatedAt, not on BrokenAt itself.
-- ❌ Letting a stale restore re-heal a mirror whose source has since been hard-deleted (rule 5 rejects it).
-- ❌ Treating 'system' writes as authoritative over human writes at exact ties — they are not (rule 4b).
-- A successful §14.2 LWW write MUST emit exactly one SSE event in the same transaction commit phase (no separate publish step that can drift) [gate: G-25-SSE-TX-ATOMIC-EMIT].

-- Source: spec/31-app/01-features/14-concurrency-and-sync.md`,
  "b3-1": `This file is the single source of truth for how concurrent edits resolve across tabs, devices, and collaborators. Every other feature (mirrors, sharing, multi-select, today, board) defers to the rules here.

-- ❌ Mutating BrokenAt without also writing BrokenAtUpdatedAt = serverNow and BrokenAtUpdatedBy.
-- ❌ Resolving "broken vs healthy" with MAX(BrokenAt) — the comparison is on BrokenAtUpdatedAt, not on BrokenAt itself.
-- ❌ Letting a stale restore re-heal a mirror whose source has since been hard-deleted (rule 5 rejects it).
-- ❌ Treating 'system' writes as authoritative over human writes at exact ties — they are not (rule 4b).
-- A successful §14.2 LWW write MUST emit exactly one SSE event in the same transaction commit phase (no separate publish step that can drift) [gate: G-25-SSE-TX-ATOMIC-EMIT].

-- Source: spec/31-app/01-features/14-concurrency-and-sync.md`,
  "b5-1": `This spec is the algorithmic SSOT for detecting mirror cycles. md (ERR_CYCLE on EP-ITEMS-MOVE).

-- Source: spec/31-app/01-features/09a-mirror-cycle-detection.md # Overview`,
  "b5-2": `| Database | Tables read/written | Notes | |---|---|---| | Root DB | — | Cycle detection is workspace-local. ParentId graph | Algorithm is a recursive CTE on App DB only.

-- Anchor: 07-db-diagram/00b-split-db-anchor.md
-- Scope: [db-scope: app]
-- Tables: mirror_groups, nodes
-- Cross-DB JOINs: forbidden (split-DB invariant). Cross-DB orchestration, if any, follows ADR-0019.
-- ADR-0023 — Loader↔Queue Contract: Loaders MUST read the local IndexedDB mirror first (≤16 ms p95, never fetch). Mutations MUST write {mirror, queue_ledger} in a single IDB transaction; the queue worker is the sole egress to the WordPress REST surface. SSE frames are read-signals only and MUST NOT enqueue to the FIFO (gates G-23-LOADER-MIRROR-FIRST, G-23-LOADER-NO-MUTATE, G-23-ACTION-ENQUEUE-ONLY). See spec/30-architecture/adr/0023-loader-queue-contract.md.

-- Source: spec/31-app/01-features/09a-mirror-cycle-detection.md # Algorithm`,
  "o1-01-slos": `The plugin runs against SQLite databases bundled inside wp-content/uploads/workflowy/. Loss of a single host means total data loss unless backups exist, are off-site, are encrypted, and have been proven restorable.

-- What is backed up (and what isn't)
-- RPO / RTO objectives per data class
-- Schedule, retention, encryption, and off-site placement
-- Restore procedure and mandatory quarterly drill
-- Audit and alerting contract

-- Source: spec/31-app/05-conventions/14-backup-and-dr-policy.md`,
  "o5-05-playbook-restore": `The plugin runs against SQLite databases bundled inside wp-content/uploads/workflowy/. Loss of a single host means total data loss unless backups exist, are off-site, are encrypted, and have been proven restorable.

-- What is backed up (and what isn't)
-- RPO / RTO objectives per data class
-- Schedule, retention, encryption, and off-site placement
-- Restore procedure and mandatory quarterly drill
-- Audit and alerting contract

-- Source: spec/31-app/05-conventions/14-backup-and-dr-policy.md`,
};
