#!/usr/bin/env bun
/**
 * Extract speaker-note seeds from spec markdown into src/deck/notes.generated.ts.
 *
 * For each entry in src/deck/note-sources.ts:
 *   1. Read the markdown file
 *   2. If `anchor` set: find the matching heading and capture until the next
 *      heading of equal-or-higher level
 *   3. Otherwise: capture the first prose section after frontmatter and skip-
 *      headings
 *   4. Pull the first paragraph (1-3 sentences) + up to 5 list bullets
 *   5. Format as `headline\n\n-- bullet\n-- bullet ...`
 *
 * Usage:  bun scripts/extract-spec-notes.ts
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { NOTE_SOURCES } from "../src/deck/note-sources";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

function stripFrontmatter(md: string): string {
  if (md.startsWith("---")) {
    const end = md.indexOf("\n---", 3);
    if (end !== -1) return md.slice(end + 4);
  }
  return md;
}

function extractSection(md: string, anchor?: string): string {
  const body = stripFrontmatter(md);
  const lines = body.split("\n");

  if (!anchor) {
    // Skip past metadata blockquotes and the first H1; capture next prose chunk.
    let i = 0;
    while (i < lines.length && !/^#{2,}\s/.test(lines[i])) i++;
    return lines.slice(i).join("\n");
  }

  const want = anchor.toLowerCase();
  let start = -1;
  let level = 0;
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(/^(#{1,6})\s+(.*)$/);
    if (m && m[2].toLowerCase().includes(want)) {
      start = i + 1;
      level = m[1].length;
      break;
    }
  }
  if (start === -1) return "";

  let end = lines.length;
  for (let i = start; i < lines.length; i++) {
    const m = lines[i].match(/^(#{1,6})\s/);
    if (m && m[1].length <= level) { end = i; break; }
  }
  return lines.slice(start, end).join("\n");
}

function summarize(section: string): { headline: string; bullets: string[] } {
  const lines = section.split("\n");
  const para: string[] = [];
  const bullets: string[] = [];
  let inCode = false;
  let inPara = false;

  for (const raw of lines) {
    const line = raw.trimEnd();
    if (line.startsWith("```")) { inCode = !inCode; continue; }
    if (inCode) continue;
    if (/^>/.test(line)) continue;       // blockquote = metadata
    if (/^#/.test(line)) continue;       // skip sub-headings
    if (/^\s*$/.test(line)) {
      if (para.length) inPara = false;
      continue;
    }
    const bm = line.match(/^\s*[-*]\s+(.*)$/);
    if (bm) {
      if (bullets.length < 5) bullets.push(cleanInline(bm[1]));
      inPara = false;
      continue;
    }
    if (para.length === 0 || inPara) {
      para.push(cleanInline(line));
      inPara = true;
    }
  }

  const fullPara = para.join(" ").trim();
  const sentences = fullPara.match(/[^.!?]+[.!?]+(\s|$)/g) ?? [fullPara];
  const headline = sentences.slice(0, 2).join("").trim() || fullPara.slice(0, 240);
  return { headline, bullets };
}

function cleanInline(s: string): string {
  return s
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .trim();
}

function format(headline: string, bullets: string[], srcPath: string): string {
  const head = headline || "(no prose found in source section)";
  const lines = [head];
  if (bullets.length) {
    lines.push("");
    for (const b of bullets) lines.push(`-- ${b}`);
  }
  lines.push("");
  lines.push(`-- Source: ${srcPath}`);
  return lines.join("\n");
}

function escapeBacktick(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function main() {
  const out: string[] = [
    "// AUTO-GENERATED by scripts/extract-spec-notes.ts — do not edit by hand.",
    "// Re-run: bun scripts/extract-spec-notes.ts",
    "// Hand-written entries in `notes.ts` always win over these.",
    "",
    "export const GENERATED_NOTES: Record<string, string> = {",
  ];

  let okCount = 0;
  let skipCount = 0;
  for (const src of NOTE_SOURCES) {
    const abs = resolve(ROOT, src.spec);
    if (!existsSync(abs)) {
      console.warn(`! missing: ${src.spec} (slide ${src.slideId})`);
      skipCount++;
      continue;
    }
    const md = readFileSync(abs, "utf8");
    const section = extractSection(md, src.anchor);
    if (!section.trim()) {
      console.warn(`! empty section: ${src.spec}${src.anchor ? ` # ${src.anchor}` : ""}`);
      skipCount++;
      continue;
    }
    const { headline, bullets } = summarize(section);
    const note = format(headline, bullets, src.spec + (src.anchor ? ` # ${src.anchor}` : ""));
    out.push(`  ${JSON.stringify(src.slideId)}: \`${escapeBacktick(note)}\`,`);
    okCount++;
  }

  out.push("};");
  out.push("");

  const outPath = resolve(ROOT, "src/deck/notes.generated.ts");
  writeFileSync(outPath, out.join("\n"));
  console.log(`✓ wrote ${outPath}`);
  console.log(`  ${okCount} extracted, ${skipCount} skipped, ${NOTE_SOURCES.length} total`);
}

main();
